### ISSUE TITLE
Scala  2.12.x ?

### ISSUE THREAD

**Issue by jose78** [milankinen/zeison#1]
Hy,

I would like to know if there is any plan to evolve it to Scala 2.12.* ?

Thnkx.

**Comment by milankinen** [comment]
Cheers!

I don't currently have any time for version upgrade, but is someone is willing to send PR, I'd happily accept it. 😊

**Comment by milankinen** [comment]
Hmm. It actually wasn't so big deal at all. I published new [0.8.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/tsers/zeison/zeison_2.12/0.8.0-SNAPSHOT) release from [`2.12.x` branch](https://github.com/tsers/zeison/tree/2.12.x), feel free to test it! 😊  If there are no problems, I'm gonna publish the actual release version.

**Comment by milankinen** [comment]
Will be released as an official release tonight.

**Comment by milankinen** [comment]
[`0.8.0`](https://github.com/tsers/zeison/releases/tag/0.8.0) released
