### ISSUE TITLE
Resolving SNAPSHOT Dependencies

### ISSUE THREAD

**Issue by prodrammer** [milankinen/zeison#2]
I'm pretty new to sbt & scala. I know this may be common knowledge, but I think it would be very helpful if you updated your README with the following:

```
resolvers += Resolver.sonatypeRepo("releases")

libraryDependencies += "org.tsers.zeison" %% "zeison" % "0.8.0"
```

vs

```
resolvers += Resolver.sonatypeRepo("snapshots")

libraryDependencies += "org.tsers.zeison" %% "zeison" % "0.8.0-SNAPSHOT"
```

Aside from that, thanks for creating this project. I'm dealing with JSON data stores and this will greatly reduce mental contention. 🥇

**Comment by milankinen** [comment]
Ah I'm so sorry I missed this issue completely! :frowning: 

I'm releasing the `0.8.0`  version as an "official" release and merging `0.12.x` to `master` tonight so there is no need to use snapshot repo anymore.

I'm glad if you have liked the library. :blush:

**Comment by milankinen** [comment]
[`0.8.0`](https://github.com/tsers/zeison/releases/tag/0.8.0) released, you can now remove the snapshot repository 😊
